name: wedding
description: Wedding Checkin App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  lottie: ^2.1.0
  # For Model
  # freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  # For Architecture MVVM
  pmvvm: ^4.0.1
  # State Management, Route Management, Dependency Management
  get: ^4.6.5
  get_storage: ^2.0.3
  # For Image Caching
  # cached_network_image: ^3.2.3
  # Staggered Grid View
  # flutter_staggered_grid_view: ^0.6.2
  # video player
  flutter_launcher_icons: ^0.11.0
  # carousel_slider: ^4.2.1
  simple_grid: ^0.1.2
  # to Generate Unique ID
  uuid: ^3.0.7
  # Camera Plugin
  camera: ^0.10.3+1
  permission_handler: ^10.2.0
  code_scan: ^0.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
   # For Model
  json_serializable: ^6.5.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/favicon.png"
    background_color: "#E25D5D"
    theme_color: "#E25D5D"
  windows:
    generate: true
    image_path: "assets/images/favicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/favicon.png"

flutter:
  uses-material-design: true
  assets:
        - assets/images/
        - assets/icons/
        - assets/icons/svg/
        - assets/animations/
        - assets/fonts/

  fonts:
        - family: SourceSansPro
          fonts:
              - asset: assets/fonts/SourceSansPro-Regular.ttf
              - asset: assets/fonts/SourceSansPro-SemiBold.ttf
              - asset: assets/fonts/SourceSansPro-Bold.ttf

        - family: PlayfairDisplay
          fonts:
              - asset: assets/fonts/PlayfairDisplay-Regular.ttf
              - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
              - asset: assets/fonts/PlayfairDisplay-Medium.ttf

        - family: OpenSans
          fonts:
              - asset: assets/fonts/OpenSans-Regular.ttf
              - asset: assets/fonts/OpenSans-SemiBold.ttf
              - asset: assets/fonts/OpenSans-Medium.ttf
              - asset: assets/fonts/OpenSans-Bold.ttf
